import { useState } from "react";
import { motion, AnimatePresence } from "motion/react";
import { 
  Megaphone, 
  Users, 
  MessageSquare, 
  Calendar, 
  Vote, 
  Copy, 
  Check, 
  Loader2, 
  Sparkles,
  ChevronRight,
  Phone,
  Target,
  FileText,
  Lightbulb,
  RefreshCw
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { ScrollArea } from "@/components/ui/scroll-area";
import { generateCampaignPack, generateSlogans, CampaignInput, CampaignOutput } from "@/services/geminiService";
import { cn } from "@/lib/utils";

export default function App() {
  const [input, setInput] = useState<CampaignInput & { slogan: string }>({
    name: "",
    position: "",
    area: "",
    message: "",
    pillars: "",
    date: "",
    contact: "",
    tone: "Inspirational & Bold",
    slogan: "",
  });

  const [sloganSuggestions, setSloganSuggestions] = useState<string[]>([]);
  const [loadingSlogans, setLoadingSlogans] = useState(false);
  const [output, setOutput] = useState<CampaignOutput | null>(null);
  const [loading, setLoading] = useState(false);
  const [copiedId, setCopiedId] = useState<string | null>(null);

  const handleGenerateSlogans = async () => {
    if (!input.message) return;
    setLoadingSlogans(true);
    try {
      const suggestions = await generateSlogans(input.message, input.tone);
      setSloganSuggestions(suggestions);
    } catch (error) {
      console.error("Slogan generation failed:", error);
    } finally {
      setLoadingSlogans(false);
    }
  };

  const handleGenerate = async () => {
    if (!input.name || !input.position) return;
    setLoading(true);
    try {
      const result = await generateCampaignPack({
        ...input,
        selectedSlogan: input.slogan
      });
      setOutput(result);
    } catch (error) {
      console.error("Generation failed:", error);
    } finally {
      setLoading(false);
    }
  };

  const copyToClipboard = (text: string, id: string) => {
    navigator.clipboard.writeText(text);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2000);
  };

  const downloadPack = () => {
    if (!output) return;

    const content = `UPND CAMPAIGN PACK - ${input.name}
=====================================
Position: ${input.position}
Area: ${input.area}
Election Date: ${input.date}
Contact: ${input.contact}

MAIN POSTER
-----------
Slogan: ${output.mainPoster.slogan}
Candidate: ${output.mainPoster.candidateName}
CTA: ${output.mainPoster.cta}

SOCIAL MEDIA POSTS
------------------
${output.socialMediaPosts.map((p, i) => `POST ${i + 1} (${p.pillar}):\n${p.content}\n`).join("\n")}

WHATSAPP FLYER
--------------
${output.whatsappFlyer.text}

EVENT ANNOUNCEMENT
------------------
Title: ${output.eventAnnouncement.title}
Details: ${output.eventAnnouncement.details}
Urgency: ${output.eventAnnouncement.urgency}

VOTING DAY MESSAGE
------------------
${output.votingDayMessage.content}

-------------------------------------
Generated by UPND Campaign Pack Generator
`;

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `UPND_Campaign_Pack_${input.name.replace(/\s+/g, "_")}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-neutral-50 flex flex-col">
      {/* Header */}
      <header className="bg-upnd-green text-white py-6 px-4 shadow-lg sticky top-0 z-50">
        <div className="max-w-7xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="bg-upnd-yellow p-2 rounded-lg">
              <Megaphone className="text-upnd-green h-6 w-6" />
            </div>
            <div>
              <h1 className="font-display text-2xl tracking-tight uppercase">UPND Campaign Pack</h1>
              <p className="text-xs text-upnd-yellow font-medium opacity-90">Professional Content Generator</p>
            </div>
          </div>
          <div className="hidden md:flex items-center gap-4">
            <Badge variant="outline" className="border-upnd-yellow text-upnd-yellow">Zambia 2026</Badge>
            <div className="h-8 w-[2px] bg-upnd-yellow/20" />
            <div className="flex gap-1">
              <div className="w-3 h-3 rounded-full bg-upnd-green border border-white/20" />
              <div className="w-3 h-3 rounded-full bg-upnd-yellow border border-white/20" />
              <div className="w-3 h-3 rounded-full bg-upnd-red border border-white/20" />
            </div>
          </div>
        </div>
      </header>

      <main className="flex-1 max-w-7xl mx-auto w-full p-4 md:p-8 grid grid-cols-1 lg:grid-cols-12 gap-8">
        {/* Input Section */}
        <div className="lg:col-span-5 space-y-6">
          <Card className="border-t-4 border-t-upnd-green shadow-md">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <FileText className="h-5 w-5 text-upnd-green" />
                Candidate Details
              </CardTitle>
              <CardDescription>Fill in the details to generate your campaign materials.</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="name">Candidate Name</Label>
                  <Input 
                    id="name" 
                    placeholder="e.g. Hakainde Hichilema" 
                    value={input.name}
                    onChange={(e) => setInput({...input, name: e.target.value})}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="position">Position</Label>
                  <Input 
                    id="position" 
                    placeholder="e.g. Member of Parliament" 
                    value={input.position}
                    onChange={(e) => setInput({...input, position: e.target.value})}
                  />
                </div>
              </div>

              <div className="space-y-2">
                <Label htmlFor="area">Constituency / Area</Label>
                <Input 
                  id="area" 
                  placeholder="e.g. Lusaka Central" 
                  value={input.area}
                  onChange={(e) => setInput({...input, area: e.target.value})}
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="message">Core Message</Label>
                <Textarea 
                  id="message" 
                  placeholder="What is your main campaign promise?" 
                  className="min-h-[80px]"
                  value={input.message}
                  onChange={(e) => setInput({...input, message: e.target.value})}
                />
              </div>

              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <Label htmlFor="slogan">Campaign Slogan</Label>
                  <Button 
                    variant="ghost" 
                    size="sm" 
                    className="h-7 text-xs text-upnd-green hover:text-upnd-green hover:bg-upnd-green/10"
                    onClick={handleGenerateSlogans}
                    disabled={loadingSlogans || !input.message}
                  >
                    {loadingSlogans ? <RefreshCw className="h-3 w-3 animate-spin mr-1" /> : <Lightbulb className="h-3 w-3 mr-1" />}
                    Suggest Slogans
                  </Button>
                </div>
                <Input 
                  id="slogan" 
                  placeholder="Enter custom slogan or select from suggestions" 
                  value={input.slogan}
                  onChange={(e) => setInput({...input, slogan: e.target.value})}
                />
                
                <AnimatePresence>
                  {sloganSuggestions.length > 0 && (
                    <motion.div 
                      initial={{ opacity: 0, height: 0 }}
                      animate={{ opacity: 1, height: "auto" }}
                      exit={{ opacity: 0, height: 0 }}
                      className="overflow-hidden"
                    >
                      <div className="flex flex-wrap gap-2 pt-2">
                        {sloganSuggestions.map((s, i) => (
                          <Badge 
                            key={i} 
                            variant="outline" 
                            className={cn(
                              "cursor-pointer hover:bg-upnd-green/5 transition-colors py-1 px-2 text-[10px] font-medium",
                              input.slogan === s ? "bg-upnd-green/10 border-upnd-green text-upnd-green" : "text-neutral-500"
                            )}
                            onClick={() => setInput({...input, slogan: s})}
                          >
                            {s}
                          </Badge>
                        ))}
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>

              <div className="space-y-2">
                <Label htmlFor="pillars">Key Pillars (One per line)</Label>
                <Textarea 
                  id="pillars" 
                  placeholder="1. Economic Reform\n2. Healthcare Access\n3. Education for All" 
                  className="min-h-[100px]"
                  value={input.pillars}
                  onChange={(e) => setInput({...input, pillars: e.target.value})}
                />
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="date">Election Date</Label>
                  <Input 
                    id="date" 
                    placeholder="e.g. August 12, 2026" 
                    value={input.date}
                    onChange={(e) => setInput({...input, date: e.target.value})}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="contact">Contact Info</Label>
                  <Input 
                    id="contact" 
                    placeholder="e.g. +260 97..." 
                    value={input.contact}
                    onChange={(e) => setInput({...input, contact: e.target.value})}
                  />
                </div>
              </div>

              <div className="space-y-2">
                <Label htmlFor="tone">Messaging Tone</Label>
                <Input 
                  id="tone" 
                  placeholder="e.g. Bold, Empathetic, Authoritative" 
                  value={input.tone}
                  onChange={(e) => setInput({...input, tone: e.target.value})}
                />
              </div>
            </CardContent>
            <CardFooter>
              <Button 
                className="w-full bg-upnd-green hover:bg-upnd-green/90 text-white font-bold py-6 text-lg"
                onClick={handleGenerate}
                disabled={loading || !input.name || !input.position}
              >
                {loading ? (
                  <>
                    <Loader2 className="mr-2 h-5 w-5 animate-spin" />
                    Strategizing...
                  </>
                ) : (
                  <>
                    <Sparkles className="mr-2 h-5 w-5" />
                    Generate Campaign Pack
                  </>
                )}
              </Button>
            </CardFooter>
          </Card>
        </div>

        {/* Output Section */}
        <div className="lg:col-span-7">
          <AnimatePresence mode="wait">
            {!output && !loading ? (
              <motion.div 
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, scale: 0.95 }}
                className="h-full flex flex-col items-center justify-center text-center p-8 border-2 border-dashed border-neutral-200 rounded-2xl bg-white/50"
              >
                <div className="bg-upnd-green/10 p-6 rounded-full mb-6">
                  <Target className="h-12 w-12 text-upnd-green opacity-40" />
                </div>
                <h3 className="text-xl font-bold text-neutral-800 mb-2">Ready to Launch?</h3>
                <p className="text-neutral-500 max-w-md">
                  Enter your candidate information on the left and click generate to create a professional content pack tailored for your constituency.
                </p>
              </motion.div>
            ) : loading ? (
              <motion.div 
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                className="h-full flex flex-col items-center justify-center p-8 space-y-4"
              >
                <div className="relative">
                  <div className="h-24 w-24 rounded-full border-4 border-upnd-green/20 border-t-upnd-green animate-spin" />
                  <div className="absolute inset-0 flex items-center justify-center">
                    <Megaphone className="h-8 w-8 text-upnd-green" />
                  </div>
                </div>
                <div className="text-center">
                  <h3 className="text-lg font-bold text-upnd-green">Generating Strategy</h3>
                  <p className="text-sm text-neutral-500">Crafting high-impact messaging for {input.name || "the candidate"}...</p>
                </div>
              </motion.div>
            ) : (
              <motion.div 
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                className="space-y-6"
              >
                <Tabs defaultValue="poster" className="w-full">
                  <TabsList className="grid grid-cols-3 md:grid-cols-5 w-full h-auto p-1 bg-neutral-100 mb-6">
                    <TabsTrigger value="poster" className="py-2 data-[state=active]:bg-upnd-green data-[state=active]:text-white">
                      <FileText className="h-4 w-4 mr-2 hidden md:inline" />
                      Poster
                    </TabsTrigger>
                    <TabsTrigger value="social" className="py-2 data-[state=active]:bg-upnd-green data-[state=active]:text-white">
                      <Users className="h-4 w-4 mr-2 hidden md:inline" />
                      Social
                    </TabsTrigger>
                    <TabsTrigger value="whatsapp" className="py-2 data-[state=active]:bg-upnd-green data-[state=active]:text-white">
                      <MessageSquare className="h-4 w-4 mr-2 hidden md:inline" />
                      WhatsApp
                    </TabsTrigger>
                    <TabsTrigger value="event" className="py-2 data-[state=active]:bg-upnd-green data-[state=active]:text-white">
                      <Calendar className="h-4 w-4 mr-2 hidden md:inline" />
                      Event
                    </TabsTrigger>
                    <TabsTrigger value="voting" className="py-2 data-[state=active]:bg-upnd-green data-[state=active]:text-white">
                      <Vote className="h-4 w-4 mr-2 hidden md:inline" />
                      Voting
                    </TabsTrigger>
                  </TabsList>

                  {/* Main Poster */}
                  <TabsContent value="poster">
                    <Card className="overflow-hidden border-none shadow-xl">
                      <div className="bg-upnd-green p-8 text-center space-y-6 min-h-[400px] flex flex-col justify-center relative">
                        {/* Decorative elements */}
                        <div className="absolute top-0 left-0 w-full h-2 bg-upnd-yellow" />
                        <div className="absolute bottom-0 left-0 w-full h-2 bg-upnd-red" />
                        
                        <motion.div 
                          initial={{ opacity: 0, scale: 0.9 }}
                          animate={{ opacity: 1, scale: 1 }}
                          className="space-y-2"
                        >
                          <h4 className="text-upnd-yellow font-display text-3xl md:text-5xl uppercase tracking-tighter leading-none">
                            {output?.mainPoster.slogan}
                          </h4>
                        </motion.div>

                        <div className="space-y-1">
                          <p className="text-white/80 text-sm uppercase tracking-[0.2em] font-bold">Vote for</p>
                          <h2 className="text-white font-display text-5xl md:text-7xl uppercase leading-none">
                            {output?.mainPoster.candidateName}
                          </h2>
                          <p className="text-upnd-yellow font-bold text-xl md:text-2xl uppercase tracking-wide">
                            For {input.position}
                          </p>
                        </div>

                        <div className="pt-4">
                          <Badge className="bg-upnd-red text-white hover:bg-upnd-red px-6 py-2 text-lg font-bold rounded-none uppercase tracking-widest">
                            {output?.mainPoster.cta}
                          </Badge>
                        </div>
                      </div>
                      <CardFooter className="bg-white p-4 flex justify-between items-center border-t">
                        <span className="text-xs font-medium text-neutral-500 uppercase tracking-wider">Poster Layout Preview</span>
                        <Button 
                          variant="ghost" 
                          size="sm" 
                          className="text-upnd-green"
                          onClick={() => copyToClipboard(`${output?.mainPoster.slogan}\n\nVote for ${output?.mainPoster.candidateName}\nFor ${input.position}\n\n${output?.mainPoster.cta}`, "poster")}
                        >
                          {copiedId === "poster" ? <Check className="h-4 w-4 mr-2" /> : <Copy className="h-4 w-4 mr-2" />}
                          Copy Text
                        </Button>
                      </CardFooter>
                    </Card>
                  </TabsContent>

                  {/* Social Media Posts */}
                  <TabsContent value="social">
                    <div className="space-y-4">
                      {output?.socialMediaPosts.map((post, idx) => (
                        <Card key={idx} className="border-l-4 border-l-upnd-green">
                          <CardHeader className="pb-2">
                            <div className="flex justify-between items-center">
                              <Badge variant="secondary" className="bg-upnd-green/10 text-upnd-green border-none">
                                Pillar: {post.pillar}
                              </Badge>
                              <Button 
                                variant="ghost" 
                                size="icon" 
                                className="h-8 w-8"
                                onClick={() => copyToClipboard(post.content, `social-${idx}`)}
                              >
                                {copiedId === `social-${idx}` ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
                              </Button>
                            </div>
                          </CardHeader>
                          <CardContent>
                            <p className="text-neutral-700 whitespace-pre-wrap leading-relaxed">
                              {post.content}
                            </p>
                          </CardContent>
                        </Card>
                      ))}
                    </div>
                  </TabsContent>

                  {/* WhatsApp Flyer */}
                  <TabsContent value="whatsapp">
                    <Card className="bg-[#25D366]/5 border-[#25D366]/20">
                      <CardHeader>
                        <CardTitle className="text-[#128C7E] flex items-center gap-2">
                          <MessageSquare className="h-5 w-5" />
                          WhatsApp Optimized
                        </CardTitle>
                      </CardHeader>
                      <CardContent>
                        <div className="bg-white p-6 rounded-xl shadow-sm border border-[#25D366]/30 max-w-sm mx-auto">
                          <div className="space-y-4 text-center">
                            <div className="w-12 h-1 w-full bg-upnd-green mx-auto rounded-full" />
                            <p className="text-neutral-800 font-bold text-lg whitespace-pre-wrap">
                              {output?.whatsappFlyer.text}
                            </p>
                            <div className="flex items-center justify-center gap-2 text-upnd-green font-bold">
                              <Phone className="h-4 w-4" />
                              <span>{input.contact}</span>
                            </div>
                          </div>
                        </div>
                      </CardContent>
                      <CardFooter className="justify-center">
                        <Button 
                          className="bg-[#25D366] hover:bg-[#128C7E] text-white"
                          onClick={() => copyToClipboard(output?.whatsappFlyer.text || "", "whatsapp")}
                        >
                          {copiedId === "whatsapp" ? <Check className="h-4 w-4 mr-2" /> : <Copy className="h-4 w-4 mr-2" />}
                          Copy for WhatsApp
                        </Button>
                      </CardFooter>
                    </Card>
                  </TabsContent>

                  {/* Event Announcement */}
                  <TabsContent value="event">
                    <Card className="border-upnd-red/20 bg-upnd-red/5">
                      <CardHeader>
                        <Badge className="w-fit bg-upnd-red mb-2 uppercase tracking-tighter">
                          {output?.eventAnnouncement.urgency}
                        </Badge>
                        <CardTitle className="text-upnd-red text-2xl font-display uppercase tracking-tight">
                          {output?.eventAnnouncement.title}
                        </CardTitle>
                      </CardHeader>
                      <CardContent className="space-y-4">
                        <div className="bg-white p-6 rounded-lg border border-upnd-red/20 shadow-sm">
                          <p className="text-neutral-800 font-medium whitespace-pre-wrap leading-relaxed">
                            {output?.eventAnnouncement.details}
                          </p>
                        </div>
                        <div className="flex items-center gap-4 text-upnd-red font-bold">
                          <div className="flex items-center gap-2">
                            <Calendar className="h-5 w-5" />
                            <span>{input.date}</span>
                          </div>
                          <Separator orientation="vertical" className="h-4 bg-upnd-red/20" />
                          <div className="flex items-center gap-2">
                            <Target className="h-5 w-5" />
                            <span>{input.area}</span>
                          </div>
                        </div>
                      </CardContent>
                      <CardFooter>
                        <Button 
                          variant="outline" 
                          className="w-full border-upnd-red text-upnd-red hover:bg-upnd-red hover:text-white"
                          onClick={() => copyToClipboard(`${output?.eventAnnouncement.title}\n\n${output?.eventAnnouncement.details}`, "event")}
                        >
                          {copiedId === "event" ? <Check className="h-4 w-4 mr-2" /> : <Copy className="h-4 w-4 mr-2" />}
                          Copy Announcement
                        </Button>
                      </CardFooter>
                    </Card>
                  </TabsContent>

                  {/* Voting Day */}
                  <TabsContent value="voting">
                    <Card className="bg-upnd-yellow/10 border-upnd-yellow">
                      <CardHeader>
                        <CardTitle className="flex items-center gap-2 text-neutral-900">
                          <Vote className="h-6 w-6 text-upnd-green" />
                          Final Call to Action
                        </CardTitle>
                      </CardHeader>
                      <CardContent>
                        <div className="relative p-8 bg-white rounded-2xl border-2 border-upnd-yellow shadow-inner overflow-hidden">
                          <div className="absolute -top-10 -right-10 w-32 h-32 bg-upnd-yellow/20 rounded-full blur-3xl" />
                          <div className="absolute -bottom-10 -left-10 w-32 h-32 bg-upnd-green/10 rounded-full blur-3xl" />
                          
                          <p className="relative z-10 text-xl md:text-2xl font-bold text-neutral-800 text-center italic leading-tight">
                            "{output?.votingDayMessage.content}"
                          </p>
                        </div>
                      </CardContent>
                      <CardFooter className="flex flex-col gap-4">
                        <Button 
                          className="w-full bg-upnd-green hover:bg-upnd-green/90 text-white font-bold py-6"
                          onClick={() => copyToClipboard(output?.votingDayMessage.content || "", "voting")}
                        >
                          {copiedId === "voting" ? <Check className="h-4 w-4 mr-2" /> : <Copy className="h-4 w-4 mr-2" />}
                          Copy Final Message
                        </Button>
                        <p className="text-xs text-center text-neutral-500 font-medium uppercase tracking-widest">
                          Send this on the morning of {input.date}
                        </p>
                      </CardFooter>
                    </Card>
                  </TabsContent>
                </Tabs>

                {/* Quick Actions */}
                <div className="flex flex-wrap gap-3 pt-4">
                  <Button 
                    className="bg-upnd-green hover:bg-upnd-green/90 text-white"
                    onClick={downloadPack}
                  >
                    Download Pack (.txt)
                  </Button>
                  <Button variant="outline" size="sm" onClick={() => window.print()} className="bg-white">
                    Print Pack
                  </Button>
                  <Button variant="outline" size="sm" onClick={() => setOutput(null)} className="bg-white text-upnd-red border-upnd-red/20 hover:bg-upnd-red/5">
                    Clear Results
                  </Button>
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </main>

      {/* Footer */}
      <footer className="bg-neutral-100 border-t py-8 px-4 mt-12">
        <div className="max-w-7xl mx-auto flex flex-col md:flex-row justify-between items-center gap-6">
          <div className="flex items-center gap-3 opacity-60">
            <Megaphone className="h-5 w-5" />
            <span className="font-display uppercase tracking-tight">UPND Campaign Pack</span>
          </div>
          <div className="flex gap-8 text-sm font-medium text-neutral-500">
            <a href="#" className="hover:text-upnd-green transition-colors">Strategy Guide</a>
            <a href="#" className="hover:text-upnd-green transition-colors">Brand Assets</a>
            <a href="#" className="hover:text-upnd-green transition-colors">Support</a>
          </div>
          <p className="text-xs text-neutral-400">
            &copy; 2026 UPND Digital Strategy Team. For internal campaign use only.
          </p>
        </div>
      </footer>
    </div>
  );
}
